language: android
jdk:
  - oraclejdk7
before_install:
  - echo "y" | android update sdk --no-ui --filter platform-tools,tools
  - echo "y" | android update sdk --no-ui --filter build-tools-20.0.0
  - echo "y" | android update sdk --no-ui --filter android-18,android-19
  - echo "y" | android update sdk --no-ui --filter addon-google_apis-google-18,extra-android-m2repository,extra-google-m2repository
  - git clone --depth=1 --branch=robolectric-2.4 git://github.com/robolectric/robolectric.git __robolectric__
  - cd __robolectric__
  - ./scripts/install-maps-jar.sh
  - ./scripts/install-support-jar.sh
  - mvn -q -B -V -DskipTests=true install
  - cd ..
  - rm -rf __robolectric__
  - mvn -q -B -V dependency:go-offline
install:
  - mvn install -DskipTests=true -B -V -Djarsigner.skip=true
script:
  - mvn test -B -V
after_script:
  - "[ $TRAVIS_TEST_RESULT -ne 0 ] && head -n 500 target/surefire-reports/*.txt"
notifications:
  irc:
    channels:
    - "irc.imaginarynet.uk#ci"
    skip_join: true

